i9300: disable profiling and UID_CPUTIME
enabling it causes bootloops, erroring like this:

java.lang.NumberFormatException: Invalid long: "13836653274865814848"
    at java.lang.Long.invalidLong(Long.java:124)
    at java.lang.Long.parse(Long.java:366)
    at java.lang.Long.parseLong(Long.java:353)
    at com.android.internal.os.KernelUidCpuTimeReader.readDelta(
        KernelUidCpuTimeReader.java:78)
    at com.android.internal.os.BatteryStatsImpl.updateCpuTimeLocked(
        BatteryStatsImpl.java:8096)
    at com.android.internal.os.BatteryStatsImpl$MyHandler
        .handleMessage(BatteryStatsImpl.java:153)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
    at com.android.server.ServiceThread.run(ServiceThread.java:46)

Change-Id: I070a6409441b6357527bfd0d4006d029f8b60f09